package es.autoocasion;
import org.springframework.beans.factory.annotation.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.*;import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;import jakarta.validation.Valid;import java.io.*;import java.nio.file.*;import java.time.*;import java.util.*;import java.util.concurrent.*;
@RestController @RequestMapping("/api/vehicles") @CrossOrigin(originPatterns="*") public class VehicleController {
 private final VehicleRepository repo; private final VehiclePublicationRepository publications; private final VehicleHistoryRepository history; private final AdminSessions sessions; private final ImageStorage images; private final List<SseEmitter> subscribers=new CopyOnWriteArrayList<>(); VehicleController(VehicleRepository repo,VehiclePublicationRepository publications,VehicleHistoryRepository history,AdminSessions sessions,ImageStorage images){this.repo=repo;this.publications=publications;this.history=history;this.sessions=sessions;this.images=images;}
 @GetMapping public List<Vehicle> all(@RequestParam(required=false) String brand,@RequestParam(required=false) String fuel,@RequestParam(required=false) Integer maxPrice){return repo.findAll().stream().peek(this::normalizeStatus).filter(v->brand==null||v.brand.equalsIgnoreCase(brand)).filter(v->fuel==null||v.fuel.equalsIgnoreCase(fuel)).filter(v->maxPrice==null||v.price<=maxPrice).toList();}
 @GetMapping(value="/stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE) public SseEmitter stream(){SseEmitter emitter=new SseEmitter(0L);subscribers.add(emitter);emitter.onCompletion(()->subscribers.remove(emitter));emitter.onTimeout(()->subscribers.remove(emitter));return emitter;}
 @GetMapping("/{id}") public Vehicle one(@PathVariable Long id){Vehicle v=repo.findById(id).orElseThrow(()->new NoSuchElementException("Vehículo no encontrado"));normalizeStatus(v);return v;}
 @GetMapping("/{id}/history") public List<VehicleHistory> vehicleHistory(@PathVariable Long id,@RequestHeader(value="Authorization",required=false) String token){guard(token);if(!repo.existsById(id))throw new NoSuchElementException("Vehículo no encontrado");return history.findTop8ByVehicleIdOrderByCreatedAtDesc(id);}
 @PostMapping public Vehicle create(@Valid @RequestBody Vehicle v,@RequestHeader(value="Authorization",required=false) String token){guard(token);normalizeStatus(v);v.createdAt=LocalDateTime.now();v.updatedAt=v.createdAt;if("PUBLISHED".equals(v.status))v.publishedAt=v.createdAt;Vehicle saved=repo.save(v);ensurePublications(saved);saved=repo.save(saved);record(saved.id,"CREATED","Vehículo añadido al inventario");notifyClients();return saved;}
 @PutMapping("/{id}") public Vehicle update(@PathVariable Long id,@Valid @RequestBody Vehicle input,@RequestHeader(value="Authorization",required=false) String token){guard(token); Vehicle current=repo.findById(id).orElseThrow(()->new NoSuchElementException("Vehículo no encontrado")); Integer previousPrice=current.price;String previousStatus=current.status;input.id=id;input.createdAt=current.createdAt;input.publications=current.publications;input.publishedAt=current.publishedAt;normalizeStatus(input);input.updatedAt=LocalDateTime.now();if(input.publishedAt==null&&"PUBLISHED".equals(input.status))input.publishedAt=input.updatedAt;Vehicle saved=repo.save(input);if(!Objects.equals(previousPrice,saved.price))record(id,"PRICE","Precio: "+previousPrice+" € → "+saved.price+" €");if(!Objects.equals(previousStatus,saved.status))record(id,"STATUS","Estado: "+previousStatus+" → "+saved.status);notifyClients();return saved;}
 @DeleteMapping("/{id}") public void delete(@PathVariable Long id,@RequestHeader(value="Authorization",required=false) String token){guard(token);repo.deleteById(id);notifyClients();}
 @PatchMapping("/{id}/sold") public Vehicle sold(@PathVariable Long id,@RequestHeader(value="Authorization",required=false) String token){guard(token);Vehicle v=one(id);String previousStatus=v.status;v.sold=!v.sold;v.status=v.sold?"SOLD":"PUBLISHED";v.updatedAt=LocalDateTime.now();if(v.publishedAt==null&&"PUBLISHED".equals(v.status))v.publishedAt=v.updatedAt;Vehicle saved=repo.save(v);record(id,"STATUS","Estado: "+previousStatus+" → "+saved.status);notifyClients();return saved;}
 @PatchMapping("/{id}/status") public Vehicle status(@PathVariable Long id,@RequestBody Map<String,String> body,@RequestHeader(value="Authorization",required=false) String token){guard(token);Vehicle v=one(id);String previousStatus=v.status;v.status=body.get("status");normalizeStatus(v);v.updatedAt=LocalDateTime.now();if(v.publishedAt==null&&"PUBLISHED".equals(v.status))v.publishedAt=v.updatedAt;Vehicle saved=repo.save(v);if(!Objects.equals(previousStatus,saved.status))record(id,"STATUS","Estado: "+previousStatus+" → "+saved.status);notifyClients();return saved;}
 @PatchMapping("/{id}/publications/{channel}") public VehiclePublication publication(@PathVariable Long id,@PathVariable PublicationChannel channel,@RequestBody Map<String,Boolean> body,@RequestHeader(value="Authorization",required=false) String token){guard(token);Vehicle vehicle=one(id);ensurePublications(vehicle);repo.save(vehicle);VehiclePublication publication=publications.findByVehicleIdAndChannel(id,channel).orElseThrow();publication.requested=Boolean.TRUE.equals(body.get("requested"));publication.state=publication.requested?"PENDING_CONFIGURATION":"DISABLED";publication.lastError=null;publication.updatedAt=java.time.LocalDateTime.now();return publications.save(publication);}
 @PostMapping("/{id}/images") public Vehicle upload(@PathVariable Long id,@RequestParam("file") MultipartFile file,@RequestHeader(value="Authorization",required=false) String token)throws IOException{guard(token);Vehicle v=one(id);v.images.add(images.store(file,"vehiculo"));v.updatedAt=LocalDateTime.now();Vehicle saved=repo.save(v);record(id,"PHOTO","Fotografía optimizada y añadida");notifyClients();return saved;}
 private void normalizeStatus(Vehicle v){String requested=v.status==null?"":v.status.toUpperCase(Locale.ROOT);if(!Set.of("DRAFT","PUBLISHED","RESERVED","SOLD").contains(requested))requested=v.sold?"SOLD":"PUBLISHED";v.status=requested;v.sold="SOLD".equals(requested);}
 private void ensurePublications(Vehicle vehicle){for(PublicationChannel channel:PublicationChannel.values()){boolean exists=vehicle.publications.stream().anyMatch(item->item.channel==channel);if(!exists){VehiclePublication item=new VehiclePublication();item.vehicle=vehicle;item.channel=channel;vehicle.publications.add(item);}}}
 private void record(Long vehicleId,String type,String detail){VehicleHistory event=new VehicleHistory();event.vehicleId=vehicleId;event.type=type;event.detail=detail;history.save(event);}
 private void notifyClients(){for(SseEmitter emitter:subscribers){try{emitter.send(SseEmitter.event().name("inventory").data("changed"));}catch(IOException exception){subscribers.remove(emitter);}}}
 private void guard(String token){if(!sessions.valid(token))throw new org.springframework.web.server.ResponseStatusException(HttpStatus.UNAUTHORIZED);}
}
